<template>
  <div class="content">
    <ul>
      <li>分类列表1</li>
      <li>分类列表2</li>
      <li>分类列表3</li>
      <li>分类列表4</li>
      <li>分类列表5</li>
      <li>分类列表6</li>
      <li>分类列表7</li>
      <li>分类列表8</li>
      <li>分类列表9</li>
      <li>分类列表10</li>
      <li>分类列表11</li>
      <li>分类列表12</li>
      <li>分类列表13</li>
      <li>分类列表14</li>
      <li>分类列表15</li>
      <li>分类列表16</li>
      <li>分类列表17</li>
      <li>分类列表18</li>
      <li>分类列表19</li>
      <li>分类列表20</li>
      <li>分类列表21</li>
      <li>分类列表22</li>
      <li>分类列表23</li>
      <li>分类列表24</li>
      <li>分类列表25</li>
      <li>分类列表26</li>
      <li>分类列表27</li>
      <li>分类列表28</li>
      <li>分类列表29</li>
      <li>分类列表30</li>
      <li>分类列表31</li>
      <li>分类列表32</li>
      <li>分类列表33</li>
      <li>分类列表34</li>
      <li>分类列表35</li>
      <li>分类列表36</li>
      <li>分类列表37</li>
      <li>分类列表38</li>
      <li>分类列表39</li>
      <li>分类列表40</li>
      <li>分类列表41</li>
      <li>分类列表42</li>
      <li>分类列表43</li>
      <li>分类列表44</li>
      <li>分类列表45</li>
      <li>分类列表46</li>
      <li>分类列表47</li>
      <li>分类列表48</li>
      <li>分类列表49</li>
      <li>分类列表50</li>
      <li>分类列表51</li>
      <li>分类列表52</li>
      <li>分类列表53</li>
      <li>分类列表54</li>
      <li>分类列表55</li>
      <li>分类列表56</li>
      <li>分类列表57</li>
      <li>分类列表58</li>
      <li>分类列表59</li>
      <li>分类列表60</li>
      <li>分类列表61</li>
      <li>分类列表62</li>
      <li>分类列表63</li>
      <li>分类列表64</li>
      <li>分类列表65</li>
      <li>分类列表66</li>
      <li>分类列表67</li>
      <li>分类列表68</li>
      <li>分类列表69</li>
      <li>分类列表70</li>
      <li>分类列表71</li>
      <li>分类列表72</li>
      <li>分类列表73</li>
      <li>分类列表74</li>
      <li>分类列表75</li>
      <li>分类列表76</li>
      <li>分类列表77</li>
      <li>分类列表78</li>
      <li>分类列表79</li>
      <li>分类列表80</li>
      <li>分类列表81</li>
      <li>分类列表82</li>
      <li>分类列表83</li>
      <li>分类列表84</li>
      <li>分类列表85</li>
      <li>分类列表86</li>
      <li>分类列表87</li>
      <li>分类列表88</li>
      <li>分类列表89</li>
      <li>分类列表90</li>
      <li>分类列表91</li>
      <li>分类列表92</li>
      <li>分类列表93</li>
      <li>分类列表94</li>
      <li>分类列表95</li>
      <li>分类列表96</li>
      <li>分类列表97</li>
      <li>分类列表98</li>
      <li>分类列表99</li>
      <li>分类列表100</li>
      <li>分类列表表表1</li>
      <li>分类列表表表2</li>
      <li>分类列表表表3</li>
      <li>分类列表表表4</li>
      <li>分类列表表表5</li>
      <li>分类列表表表6</li>
      <li>分类列表表表7</li>
      <li>分类列表表表8</li>
      <li>分类列表表表9</li>
      <li>分类列表表表10</li>
      <li>分类列表表表11</li>
      <li>分类列表表表12</li>
      <li>分类列表表表13</li>
      <li>分类列表表表14</li>
      <li>分类列表表表15</li>
      <li>分类列表表表16</li>
      <li>分类列表表表17</li>
      <li>分类列表表表18</li>
      <li>分类列表表表19</li>
      <li>分类列表表表20</li>
      <li>分类列表表表21</li>
      <li>分类列表表表22</li>
      <li>分类列表表表23</li>
      <li>分类列表表表24</li>
      <li>分类列表表表25</li>
      <li>分类列表表表26</li>
      <li>分类列表表表27</li>
      <li>分类列表表表28</li>
      <li>分类列表表表29</li>
      <li>分类列表表表30</li>
      <li>分类列表表表31</li>
      <li>分类列表表表32</li>
      <li>分类列表表表33</li>
      <li>分类列表表表34</li>
      <li>分类列表表表35</li>
      <li>分类列表表表36</li>
      <li>分类列表表表37</li>
      <li>分类列表表表38</li>
      <li>分类列表表表39</li>
      <li>分类列表表表40</li>
      <li>分类列表表表41</li>
      <li>分类列表表表42</li>
      <li>分类列表表表43</li>
      <li>分类列表表表44</li>
      <li>分类列表表表45</li>
      <li>分类列表表表46</li>
      <li>分类列表表表47</li>
      <li>分类列表表表48</li>
      <li>分类列表表表49</li>
      <li>分类列表表表50</li>
      <li>分类列表表表51</li>
      <li>分类列表表表52</li>
      <li>分类列表表表53</li>
      <li>分类列表表表54</li>
      <li>分类列表表表55</li>
      <li>分类列表表表56</li>
      <li>分类列表表表57</li>
      <li>分类列表表表58</li>
      <li>分类列表表表59</li>
      <li>分类列表表表60</li>
      <li>分类列表表表61</li>
      <li>分类列表表表62</li>
      <li>分类列表表表63</li>
      <li>分类列表表表64</li>
      <li>分类列表表表65</li>
      <li>分类列表表表66</li>
      <li>分类列表表表67</li>
      <li>分类列表表表68</li>
      <li>分类列表表表69</li>
      <li>分类列表表表70</li>
      <li>分类列表表表71</li>
      <li>分类列表表表72</li>
      <li>分类列表表表73</li>
      <li>分类列表表表74</li>
      <li>分类列表表表75</li>
      <li>分类列表表表76</li>
      <li>分类列表表表77</li>
      <li>分类列表表表78</li>
      <li>分类列表表表79</li>
      <li>分类列表表表80</li>
      <li>分类列表表表81</li>
      <li>分类列表表表82</li>
      <li>分类列表表表83</li>
      <li>分类列表表表84</li>
      <li>分类列表表表85</li>
      <li>分类列表表表86</li>
      <li>分类列表表表87</li>
      <li>分类列表表表88</li>
      <li>分类列表表表89</li>
      <li>分类列表表表90</li>
      <li>分类列表表表91</li>
      <li>分类列表表表92</li>
      <li>分类列表表表93</li>
      <li>分类列表表表94</li>
      <li>分类列表表表95</li>
      <li>分类列表表表96</li>
      <li>分类列表表表97</li>
      <li>分类列表表表98</li>
      <li>分类列表表表99</li>
      <li>分类列表表表100</li>
    </ul>
  </div>
</template>

<script>
import Bscroll from "better-scroll";
export default {
  name: "Category",
  data() {
    return {
      scroll: null,
    };
  },
  mounted() {
    this.scroll = new Bscroll(document.querySelector(".content"), {
      click: true,
      //probeType:{1:不监听滚动；2：不监听滚动惯性；3：监听滚动}
      probeType: 3,
      pullUpLoad: true, //上拉加载更多
    });
    this.scroll.on("scroll", (position) => {
      console.log(position);
    });
    this.scroll.on();
  },
};
</script>

<style>
.content {
  height: 200px;
  overflow: hidden;
}
</style>